// <auto-generated />
using System;
using Findora.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Findora.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261002135358_UniqueCatalogName")]
    partial class UniqueCatalogName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Findora.Catalog.Infrastructure.Persistence.Entities.CatalogFieldRecord", b =>
                {
                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean")
                        .HasColumnName("is_array");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("CatalogId", "Name")
                        .HasName("pk_field_definitions");

                    b.ToTable("field_definitions", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_field_definitions_name_not_empty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_field_definitions_type", "type IN ('Int', 'Decimal', 'String', 'Bool')");
                        });
                });

            modelBuilder.Entity("Findora.Catalog.Infrastructure.Persistence.Entities.CatalogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name")
                        .HasComputedColumnSql("lower(btrim(name))", true);

                    b.HasKey("Id")
                        .HasName("pk_catalogs");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_catalogs_normalized_name");

                    b.ToTable("catalogs", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalogs_name_not_empty", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Findora.Catalog.Infrastructure.Persistence.Entities.CatalogFieldRecord", b =>
                {
                    b.HasOne("Findora.Catalog.Infrastructure.Persistence.Entities.CatalogRecord", null)
                        .WithMany("Fields")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_definitions_catalogs");
                });

            modelBuilder.Entity("Findora.Catalog.Infrastructure.Persistence.Entities.CatalogRecord", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
