<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Queries\" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <ProjectReference Include="../../../shared/Findora.Shared.Abstraction/Findora.Shared.Abstraction.csproj" />
    </ItemGroup>

</Project>
